Alex Mei \\
CS 165B \\
Fall 2021 \\

In [ ]:
# Imports
import numpy as np
import numpy.linalg as npla
import matplotlib.pyplot as plt
import matplotlib.patches as mpatches
from cvxopt import matrix, solvers
import random
import math
import time

solvers.options['show_progress'] = False

In [ ]:
# 3a. Hard Margin SVM implementation
def hardMarginSVM(X: np.array, y: np.array) -> np.array:
  n, d = np.shape(X)

  # build Q matrix
  Q = np.eye(d+1)
  Q[0, 0] = 0
  Q = matrix(Q)

  # build p vector
  p = matrix(np.zeros((d+1)))

  # build A matrix
  A = matrix(np.concatenate((y, y * X), axis=1), tc='d')

  # build c vector
  c = matrix(np.ones(n))

  # use qp solve
  return np.array(A), np.array(solvers.qp(P=Q, q=p, G=-A, h=-c)["x"])

In [ ]:
# In Class Example:
X = np.array([[0, 0], [2, 2], [2, 0], [3, 0]])
y = np.array([[-1], [-1], [1], [1]])
A, u = hardMarginSVM(X, y)
print("Bias: \n{}, \nWeights: \n{}".format(u[0], u[1:]))
print("A @ u: \n{}".format(A @ u))

Bias: 
[-1.00000001], 
Weights: 
[[ 1.00000001]
 [-1.00000001]]
A @ u: 
[[1.00000001]
 [1.00000002]
 [1.        ]
 [2.00000001]]


In [ ]:
# Homework Problem:
X = np.array([[0, 0], [0, -1], [-2, 0]])
y = np.array([[-1], [-1], [1]])
A, u = hardMarginSVM(X, y)
print("Bias: \n{}, \nWeights: \n{}".format(u[0], u[1:]))
print("A @ u: \n{}".format(A @ u))

Bias: 
[-1.00000001], 
Weights: 
[[-1.00000001e+00]
 [ 3.93128191e-04]]
A @ u: 
[[1.00000001]
 [1.00039314]
 [1.00000001]]


In [ ]:
# random numbers between 1 and 1000 as possible values
def generateData(sampleSize: int, features: int) -> list:
  return [[random.randint(1, 1000) for i in range(features)] for j in range(sampleSize)]

# use linear seperator x[0] >= 500 to classify classes
def generateLabels(dataset: list) -> list:
  return [[1] if sample[0] >= 500 else [-1] for sample in dataset]

In [ ]:
# 3b. Time Complexity Investigation
dataset = generateData(10, 2)
labels = generateLabels(dataset)
SAMPLE_SIZES = [10, 100, 1000, 10000, 100000, 1000000]
FEATURE_SIZES = [10, 100, 1000, 10000]

# Sample Size
for i in SAMPLE_SIZES:
  print("Sample Size: {}".format(i))
  X = np.array(generateData(i, FEATURE_SIZES[0]))
  y = generateLabels(X)

  t = time.time()
  A, u = hardMarginSVM(X, y)
  print("Runtime: {:.4f}".format(time.time() - t))

# Feature Size
for i in FEATURE_SIZES:
  print("Feature Size: {}".format(i))
  X = np.array(generateData(SAMPLE_SIZES[0], i))
  y = generateLabels(X)

  t = time.time()
  A, u = hardMarginSVM(X, y)
  print("Runtime: {:.4f}".format(time.time() - t))

Sample Size: 10
Runtime: 0.0079
Sample Size: 100
Runtime: 0.0055
Sample Size: 1000
Runtime: 0.0196
Sample Size: 10000
Runtime: 0.2222
Sample Size: 100000
Runtime: 4.0301
Sample Size: 1000000
Runtime: 20.5474
Feature Size: 10
Runtime: 0.0159
Feature Size: 100
Runtime: 0.0041
Feature Size: 1000
Runtime: 0.2485
Feature Size: 10000
Runtime: 72.6673
